export const Choices = {
	HardwareKey: [
		//main keypad
		{ id: 'zero', label: '0' },
		{ id: 'one', label: '1' },
		{ id: 'two', label: '2' },
		{ id: 'three', label: '3' },
		{ id: 'four', label: '4' },
		{ id: 'five', label: '5' },
		{ id: 'six', label: '6' },
		{ id: 'seven', label: '7' },
		{ id: 'eight', label: '8' },
		{ id: 'nine', label: '9' },
		{ id: 'period', label: '.' },
		{ id: 'at', label: '@' },
		{ id: 'minus', label: '-' },
		{ id: 'plus', label: '+' },
		{ id: 'slash', label: '/' },
		{ id: 'thru', label: 'Thru' },
		{ id: 'full', label: 'Full' },
		{ id: 'backspace', label: 'Backspace' },
		{ id: 'enter', label: 'Enter' },
		//navigation
		{ id: 'back', label: 'Back' },
		{ id: 'all', label: 'All' },
		{ id: 'next', label: 'Next' },
		{ id: 'highlight', label: 'Highlight' },
		{ id: 'blind', label: 'Blind' },
		{ id: 'clear', label: 'Clear' },
		{ id: 'up', label: 'Up' },
		{ id: 'down', label: 'Down' },
		{ id: 'left', label: 'Left' },
		{ id: 'right', label: 'Right' },
		//programming
		{ id: 'live', label: 'Live' },
		{ id: 'scene', label: 'Scene' },
		{ id: 'cue', label: 'Cue' },
		{ id: 'macro', label: 'Macro' },
		{ id: 'list', label: 'List' },
		{ id: 'page', label: 'Page' },
		{ id: 'delete', label: 'Delete' },
		{ id: 'move', label: 'Move' },
		{ id: 'copy', label: 'Copy' },
		{ id: 'update', label: 'Update' },
		{ id: 'merge', label: 'Merge' },
		{ id: 'record', label: 'Record' },
		{ id: 'setup', label: 'Setup' },
		{ id: 'goto', label: 'Goto' },
		{ id: 'set', label: 'Set' },
		{ id: 'pig', label: 'Pig' },
		{ id: 'fan', label: 'Fan' },
		{ id: 'open', label: 'Open' },
		//palettes
		{ id: 'intensity', label: 'Intensity' },
		{ id: 'position', label: 'Position' },
		{ id: 'colour', label: 'Colour' },
		{ id: 'beam', label: 'Beam' },
		{ id: 'effect', label: 'Effect' },
		{ id: 'time', label: 'Time' },
		{ id: 'group', label: 'Group' },
		{ id: 'fixture', label: 'Fixture' },
		//playback
		{ id: 'maingo', label: 'Main Play' },
		{ id: 'mainhalt', label: 'Main Halt' },
		{ id: 'mainback', label: 'Main Back' },
		{ id: 'mainchoose', label: 'Center Choose' },
		{ id: 'skipfwd', label: 'Skip Forward' },
		{ id: 'skipback', label: 'Skip Back' },
		{ id: 'assert', label: 'Assert' },
		{ id: 'release', label: 'Release' },
		{ id: 'restore', label: 'Restore' },
		{ id: 'rate', label: 'Rate' },
	],
	MasterKey: [
		{ id: 'choose', label: 'Choose' },
		{ id: 'go', label: 'Go' },
		{ id: 'pause', label: 'Pause' },
		{ id: 'goback', label: 'Back' },
		{ id: 'flash', label: 'Flash' },
	],
	NoteState: [
		{ id: 'on', label: 'Note On' },
		{ id: 'off', label: 'Note Off' },
	],
	PlaybackType: [
		{ id: '0', label: 'Cuelist' },
		{ id: '1', label: 'Scene' },
		{ id: '2', label: 'Macro' },
	],
	UpDown: [
		{ id: '1', label: 'Press' },
		{ id: '0', label: 'Release' },
	],
}

export const Fields = {
	Action: {
		type: 'dropdown',
		label: 'Action',
		id: 'action',
		choices: Choices.UpDown,
		default: '1',
	},
	Cue: {
		type: 'number',
		label: 'Cue',
		id: 'qId',
		default: 1,
		min: 1,
		max: 32768,
		required: true,
		range: false,
	},
	Cuelist: {
		type: 'number',
		label: 'Cuelist',
		id: 'qlId',
		default: 1,
		min: 1,
		max: 32768,
		required: true,
		range: false,
	},
	HardwareKey: {
		type: 'dropdown',
		label: 'Key',
		id: 'type',
		choices: Choices.HardwareKey,
		default: 'pig',
	},
	HKey: {
		type: 'number',
		label: 'H Key Number',
		id: 'hId',
		default: 1,
		min: 1,
		required: true,
		range: false,
	},
	Key: {
		type: 'dropdown',
		label: 'Key',
		id: 'type',
		choices: Choices.MasterKey,
		default: 'go',
	},
	Level: {
		type: 'number',
		label: 'Fader Level',
		tooltip: '0-255',
		id: 'level',
		default: 255,
		min: 0,
		max: 255,
		required: true,
		range: true,
	},
	Master: {
		type: 'number',
		label: 'Master Number',
		tooltip: '0 = GM, 1-90',
		id: 'mId',
		default: 1,
		min: 0,
		max: 90,
		required: true,
		range: false,
	},
	MidiAction: {
		type: 'dropdown',
		label: 'Action',
		id: 'action',
		choices: Choices.NoteState,
		default: 'on',
	},
	MidiChannel: {
		type: 'number',
		label: 'Channel #',
		id: 'cId',
		default: 1,
		min: 1,
		max: 16,
		required: true,
		range: true,
	},
	MidiNote: {
		type: 'number',
		label: 'Note #',
		id: 'nId',
		default: 1,
		min: 1,
		max: 128,
		required: true,
		range: true,
	},
	MidiVelocity: {
		type: 'number',
		label: 'Velocity (0 is treated as a Note Off)',
		id: 'velocity',
		default: 127,
		min: 0,
		max: 127,
		required: true,
		range: true,
	},
	Number: {
		type: 'number',
		label: 'Number',
		id: 'num',
		default: 1,
		min: 1,
		max: 1000,
		required: true,
		range: false,
	},
	Type: {
		type: 'dropdown',
		label: 'Type',
		id: 'type',
		choices: Choices.PlaybackType,
		default: '0',
	},
}

export const Presets = {
	Actions: [
		{ id: 'go', label: 'Go' },
		{ id: 'halt', label: 'Halt' },
		{ id: 'release', label: 'Release' },
		{ id: 'resume', label: 'Resume' },
	],
	FaderLevel: [
		{ id: '0', label: '0%' },
		{ id: '127', label: '50%' },
		{ id: '255', label: '100%' },
	],
}
